---
sections:
  - label: Games
    name: games
    path: content/games
    templates:
      - game
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Years
    name: years
    path: content/years
    templates:
      - year
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
