---
label: Year
name: year
fields:
  - type: text
    label: Title
    name: title
  - type: textarea
    label: Deck
    name: deck
  - name: games
    label: Games
    type: list
    config:
      source:
        type: pages
        section: games
